# Configuration for VPack

# This will auto-update the resourcepack link from GitHub releases based on interval in seconds
github:
  enabled: false
  interval: 600
  username: "Alathra"
  repository: "Alathra-Resourcepack"

pack-info:
  # Whether or not the resource pack must be installed, declining will kick the player
  required: true

  # Customizable prompt message
  prompt: "<red><bold>Please download the resource pack!"